# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

references:
  target_branches: &target_branches
    filters:
      branches:
        only:
          - new-master

jobs:
  build:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: 
          name: "install"
          command: |
            yarn --frozen-lockfile
      - save_cache:
          paths:
            - ~/node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      - run: 
          name: "Build"
          command: |
            yarn run lint
            yarn run coverage
            yarn run build
      
      - run:
          name: "Verify"
          command: |
            git diff --quiet --exit-code
  publish:
    docker:
      - image: circleci/node:10.6.0

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Setup git user"
          command: |
            git config --global user.email "info@unit8.co"
            git config --global user.name "Unit8 Bot"
      - run: 
          name: "Pre Publish"
          command: |
            yarn config set version-git-message "Publish v%s [ci skip]"
            yarn version --minor
      
      - run:
          name: "Push tags"
          command: |
            git push ${CIRCLE_REPOSITORY_URL} ${CIRCLE_BRANCH} --tags
workflows:
  version: 2
  unit8-infra-mui_datatables-workflow:
    jobs:
      - build:
          context: org-global
      - publish:
          <<: *target_branches
          context: org-global
          requires:
            - build